# This is a basic workflow to help you get started with Actions

name: Message Commit

on:
  issues: 
    types: opened


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write # Grant the workflow write permission for issues
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        
      # Runs a single command using the runners shell
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Run a one-line script
        run: |
          echo "$NOW - ${{ github.event.issue.title }} - ${{ github.event.issue.body }}" >> current.log  


      - name: Commit changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add .
          git commit -m "adding message"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Close Issue
        env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           REPO: ${{ github.repository }}
           ISSUE: ${{ github.event.issue.number }} # The number of the current issue
        run: |
           gh issue close "$ISSUE" --repo "$REPO" --comment "Automatically closing this issue as completed."
